### ISSUE TITLE
Error permission storage

### ISSUE THREAD

**Issue by helio-cg** [jackbrycesmith/laravel-caprover-template#3]
without executing a deploy it always returns the same permission error in the storage directory

**Comment by helio-cg** [comment]
thank you very much, this error is already solved

**Comment by germanllop** [comment]
There's an issue when the crontab generate log files, those files are owned by root because of the crontab that executes it and when there is an actual error it can't be logged because the application can't access that log file created by the crontab schedule, you can avoid it echoing that line to the user that executes the web server:

RUN (crontab -l ; echo "* * * * * /usr/local/bin/php /srv/app/artisan schedule:run >> /dev/null 2>&1") | crontab -u <webserver_username> -
